[package]
name = "shipc"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea.lattuada@inf.ethz.ch>"]

[dependencies]
clap = "^2.25"
tempdir = "0.3"
rand = "0.3"
base32 = "^0.3.1"
serde_json = "1.0"
